import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useSession, signIn, signOut } from 'next-auth/client';

export default function Home() {
  const [session, loading] = useSession();
  const renderAuthButtons = () => {
    if (session) {
      return (
        <>
          <div>You are logged in with Email -  apoorvtaneja@outlook.com</div>
          <button className={styles.logoutButton} onClick={() => signOut()}>
            Logout
          </button>
        </>
      );
    } else {
      return (
        <button className={styles.loginButton} onClick={() => signIn()}>
          Login
        </button>
      );
    }
  };
  if (loading) {
    return <div>Loading...</div>;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{' '}
          <a href="https://github.com/plxity/Next-auth-starter">
            NextAuth.js template!
          </a>
        </h1>
        <div className={styles.infoContainer}>
        Hello 👋, This is a basic setup of NextAuth.js code. You can try using the login and logout functionality after adding the secret key&apos;s in the <code>.env.local</code> file and can make changes as per the requirements.
        </div>
        <div className={styles.authContainer}>{renderAuthButtons()}</div>
      </main>
    </div>
  );
}
